// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "speechrecognition.h"

/////////////////////////////////////////////////////////////////////////////
// CSpeechRecognition

IMPLEMENT_DYNCREATE(CSpeechRecognition, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSpeechRecognition properties

long CSpeechRecognition::GetVolume()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CSpeechRecognition::SetVolume(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CSpeechRecognition::GetRate()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CSpeechRecognition::SetRate(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

CString CSpeechRecognition::GetLicenseKey()
{
	CString result;
	GetProperty(0x12, VT_BSTR, (void*)&result);
	return result;
}

void CSpeechRecognition::SetLicenseKey(LPCTSTR propVal)
{
	SetProperty(0x12, VT_BSTR, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSpeechRecognition operations

void CSpeechRecognition::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CSpeechRecognition::Speak(LPCTSTR strText)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strText);
	return result;
}

void CSpeechRecognition::InitControl()
{
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CSpeechRecognition::GetVoiceCount()
{
	long result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CSpeechRecognition::GetVoiceName(long index)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		index);
	return result;
}

void CSpeechRecognition::SetSelectedVoice(long index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 index);
}

BOOL CSpeechRecognition::SpeakFromText(LPCTSTR strTextFile)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strTextFile);
	return result;
}

BOOL CSpeechRecognition::SpeakFromWaveFile(LPCTSTR strWaveFile)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strWaveFile);
	return result;
}

void CSpeechRecognition::Pause()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CSpeechRecognition::Resume()
{
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CSpeechRecognition::SpeakToWave(LPCTSTR strText, LPCTSTR strWaveFile)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strText, strWaveFile);
	return result;
}

BOOL CSpeechRecognition::SpeakFromTextToWave(LPCTSTR strTextFile, LPCTSTR strWaveFile)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strTextFile, strWaveFile);
	return result;
}

long CSpeechRecognition::GetOutputWaveFormatCount()
{
	long result;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CSpeechRecognition::GetOutputWaveFormatName(long index)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		index);
	return result;
}

void CSpeechRecognition::SetSelectedOutputWaveFormat(long index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 index);
}

void CSpeechRecognition::Stop()
{
	InvokeHelper(0x13, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
