#if !defined(AFX_SPEECHRECOGNITION_H__1C7F4CD5_CC3B_46AC_9317_7087C5992205__INCLUDED_)
#define AFX_SPEECHRECOGNITION_H__1C7F4CD5_CC3B_46AC_9317_7087C5992205__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSpeechRecognition wrapper class

class CSpeechRecognition : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSpeechRecognition)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5cc68366, 0xda48, 0x4659, { 0xb1, 0x38, 0x62, 0x58, 0x8e, 0x82, 0xb2, 0x1e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetVolume();
	void SetVolume(long);
	long GetRate();
	void SetRate(long);
	CString GetLicenseKey();
	void SetLicenseKey(LPCTSTR);

// Operations
public:
	void AboutBox();
	BOOL Speak(LPCTSTR strText);
	void InitControl();
	long GetVoiceCount();
	CString GetVoiceName(long index);
	void SetSelectedVoice(long index);
	BOOL SpeakFromText(LPCTSTR strTextFile);
	BOOL SpeakFromWaveFile(LPCTSTR strWaveFile);
	void Pause();
	void Resume();
	BOOL SpeakToWave(LPCTSTR strText, LPCTSTR strWaveFile);
	BOOL SpeakFromTextToWave(LPCTSTR strTextFile, LPCTSTR strWaveFile);
	long GetOutputWaveFormatCount();
	CString GetOutputWaveFormatName(long index);
	void SetSelectedOutputWaveFormat(long index);
	void Stop();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SPEECHRECOGNITION_H__1C7F4CD5_CC3B_46AC_9317_7087C5992205__INCLUDED_)
